---
- name: "create backend"
  file:
    path: ~/backend-app
    state: directory

- name: "unarchive backend"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "install node"
  shell: |
   cd ~/backend-app
   npm i
 
- name: "Executing node"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node
- name: "print message"
  debug: 
    msg: "{{ execute_node.stdout_lines }}"

- name: "configure pm2"
  become: true
  shell: |
    env path=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu